apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: sites.intre.com
spec:
  group: intre.com
  names:
    kind: Site
    listKind: SiteList
    plural: sites
    singular: site
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        properties:
          status:
            nullable: false
            properties:
              status:
                nullable: false
                type: string
            type: object
          spec:
            nullable: false
            properties:
              name:
                nullable: false
                type: string
              address:
                nullable: false
                type: string
              message:
                nullable: false
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}